baseURL = "https://nfteam.netlify.com/"
languageCode = "en-us"
title = "NeckFire Team Official Website"
theme = "hugo-theme-dimension-master"
[module]
[[module.imports]]
  path = 'github.com/hugomods/pwa'

[[params.social]]
  name = "github"
  url = "https://github.com/neckfire"

[[params.social]]
  name = "discord"
  url = "https://discord.gg/AzdjSztF4C"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
