const names = [
"John Smith",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Louka Bobinski",
"Donald Trump",
"Emmanuel Macaron",
"Emmanuel Macaron",
"Emmanuel Macaron",
"Emmanuel Macaron",
"Emmanuel Macaron",
"Samantha Lee",
"David Kim",
"Emily Chen",
"Michael Johnson",
"Jessica Brown",
"James Wilson",
"Ashley Davis",
"Daniel Garcia",
"Isabella Martinez",
"William Rodriguez",
"Sophia Hernandez",
"Joseph Nguyen",
"Victoria Jackson",
"Robert Miller",
"Olivia Moore",
"Christopher Jones",
"Ava Taylor",
"Matthew Anderson",
"Elizabeth Perez",
"Andrew Martin",
"Mia Thompson",
"Joshua White",
"Emma Harris",
"Ryan Martin",
"Ella King",
"Brandon Wright",
"Madison Walker",
"Tyler Robinson",
"Abigail Mitchell",
"Nicholas Hill",
"Chloe Nelson",
"Alexander Baker",
"Grace Cooper",
"Jonathan Green",
"Lily Parker",
"Kevin Adams",
"Avery Collins",
"Brian Campbell",
"Hailey Stewart",
"Eric Stewart",
"Amelia Phillips",
"Jacob Turner",
"Sofia Flores",
"Benjamin Carter",
"Leah Reed",
"Zachary Cook",
"Natalie Bailey",
"Samuel Rivera",
"Scarlett Parker",
"Anthony Cooper",
"Lucy Evans",
"Jaden Kelly",
"Audrey Diaz",
"Tristan Murphy",
"Gabriella Perez",
"Austin Jenkins",
"Ariana Sanchez",
"Cameron Rogers",
"Maya Ross",
"Philip Foster",
"Ella Kim",
"Lauren Ramirez",
"Adam Wright",
"Caroline Ortiz",
"Jonathan Lee",
"Avery Hernandez",
"Alexa Ruiz",
"Tyler Davis",
"Zoe Gonzales",
"Charles Brown",
"Savannah Lee",
"David Kim",
"Lila Nguyen",
"Michaela Baker",
"John Doe",
"Jane Smith",
"Jack Johnson",
"Jill Williams",
"Luke Thompson",
"Lucy Johnson",
"Peter Parker",
"Mary Jane Watson",
"Clark Kent",
"Lois Lane",
"Tony Stark",
"Pepper Potts",
"Steve Rogers",
"Peggy Carter",
"Thor Odinson",
"Jane Foster",
"Natasha Romanoff",
"Clint Barton",
"Thor",
"Groot",
"Mantis",
"Thanos",
"Maxime",
"Maxime",
"Maxime",
"Maxime",
"Maxime",
"Maxime",
];

const nameContainer = document.getElementById("name");
const generateBtn = document.getElementById("generate-btn");

generateBtn.addEventListener("click", function() {
  const randomName = names[Math.floor(Math.random() * names.length)];
  // Update the text content of the name container with the random name
  nameContainer.textContent = randomName;
  const impostorContainer = document.getElementById("impostor-container");
  impostorContainer.style.display = "none";
});

function checkName() {
  const nameSpan = document.getElementById("name");
  if (nameSpan.innerText === "Louka Bobinski") {
    const impostorContainer = document.getElementById("impostor-container");
    impostorContainer.style.display = "block";
  }
  if (nameSpan.innerText === "Maxime") {
    const pillowContainer = document.getElementById("pillow-container");
    impostorContainer.style.display = "block";
  }
}
